name: liquid_progress_indicator
description: A liquid progress indicator for Flutter.
version: 0.0.1
author: "Jordan Davies <jordandavies1990@live.co.uk>"
homepage: "https://github.com/JordanADavies/liquid_progress_indicator"

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
